### DISCUSSION TITLE
Temporarily disable background blur/transparency

### DISCUSSION THREAD

**Discussion by iridris** [Madelena/Metrology-for-Hass#14] [General]
Is there a way I can temporarily modify my installation to turn off the background transparency? I use Firefox as my primary browser, but unfortunately Firefox has disabled the ability to render background blur for a few months while they refactor the code. With the transparency enabled, but with no background blur present - it is a bit difficult to read some of the text.

Firefox bug tracking the code refactoring: https://bugzilla.mozilla.org/show_bug.cgi?id=1749625

**Comment by Madelena** [comment]
Yes, to temporarily modify it, you can look for these lines in `metro.yaml` and remove them:

```yaml
      .mdc-dialog__surface {
        backdrop-filter: blur(8px);
        background-color: rgba(var(--rgb-mdc-theme-surface), .5) !important;
      }
```

```yaml
      app-header, app-toolbar {
        backdrop-filter: blur(8px);
      }
```

Also look for:
```yaml
  app-header-background-color: "rgb(255,255,255,.33)"
```

And change it into:
```yaml
  app-header-background-color: "rgb(255,255,255,1)"
```
