### ISSUE TITLE
Feature Request: Separate light and dark themes.

### ISSUE THREAD

**Issue by DarkFox** [Madelena/Metrology-for-Hass#34]
It would be great to have separated out light and dark themes.

I'm one of those dinosaurs still using automations, to change the theme for all devices, regardless of their "dark mode" setting (in fact, some of my wall mounted tablets don't even support it).

Currently, I'm getting by, by manually editing the theme after every update, but it would be nice to have as standard.

This is the modification I use currently:

```yaml

Metro Blue Light: &metro-blue-light
  <<: *metro-common-light

  primary-color: "#0078d7"
  rgb-primary-color: "0,120,215"
  rgb-primary-color-darker: "0,91,163"
  rgb-primary-color-lighter: "0,141,253"
  hue-primary-color: "207deg"

  accent-color: "#008dfd"
  rgb-accent-color: "0,141,253"

  card-mod-theme: "Metro Blue Light"

Metro Blue Dark: &metro-blue-dark
  <<: *metro-common-dark

  primary-color: "#0078d7"
  rgb-primary-color: "0,120,215"
  rgb-primary-color-darker: "0,91,163"
  rgb-primary-color-lighter: "0,141,253"
  hue-primary-color: "207deg"

  accent-color: "#008dfd"
  rgb-accent-color: "0,141,253"

  card-mod-theme: "Metro Blue Dark"
```
