### ISSUE TITLE
Section separator is now just a small spacer?

### ISSUE THREAD

**Issue by igorsantos07** [Madelena/Metrology-for-Hass#66]
Originally the section separator of the Entities card was a visible `<hr>`, but now it's just a space slightly bigger than the usual between entities. Is this intentional, or a bug?

This way, it really doesn't help much to create separate sections inside the card... :(

![image](https://github.com/Madelena/Metrology-for-Hass/assets/532299/7c941ad8-07b8-44ca-ab00-236a7993b6c5) ![image](https://github.com/Madelena/Metrology-for-Hass/assets/532299/214b6800-a6cf-474b-8667-5f6fa3b29898)
The last entity is supposedly on its own section on the first screenshot.

**Comment by Madelena** [comment]
Can you show me the YAML you used to create the example you showed above? Thanks :)

**Comment by igorsantos07** [comment]
It's just [this](https://www.home-assistant.io/dashboards/entities#divider)

```yaml
type: entities
entities:
  - entity: number.alimentador_racao
  - type: divider
  - entity: input_datetime.sache
```

So far, it seems fixed, though haha
![image](https://github.com/Madelena/Metrology-for-Hass/assets/532299/1ee61c1c-4790-4fbc-a8d8-7530a2dab088)
