### ISSUE TITLE
ha-attribute-value incorrectly set as H2 and not body text

### ISSUE THREAD

**Issue by twcau** [Madelena/Metrology-for-Hass#71]
As shown below, I am observing a behaviour with Metrology (in all colour schemes) where the values of attribute text (ha-attribute-value, DIV = value) shown in the attributes portion of a view is being rendered as a H2, and not a body font.

This is seemingly caused by ha-attribute-value being rendered as a H2, with the following values:
`    --h2-font-size: 2.25rem;`

![Screenshot 2023-11-25 121624](https://github.com/Madelena/Metrology-for-Hass/assets/34460650/dee0bb8c-4152-473c-ab30-384fcbce9e60)

**Comment by zanix** [comment]
I think I found where this size is defined for the attributes

Find this in metro.yaml
```css
.data-entry .value {
  text-align: left !important;
  font-size: var(--h2-font-size);
  font-weight: var(--h2-font-weight);
  line-height: 1.1;
  margin-bottom: 16px;
  max-width: none !important;
}
```

And comment out the `font-*` values
```css
.data-entry .value {
  text-align: left !important;
  /*font-size: var(--h2-font-size);*/
  /*font-weight: var(--h2-font-weight);*/
  line-height: 1.1;
  margin-bottom: 16px;
  max-width: none !important;
}
```

I didn't test all of the more info popups, so hopefully this doesn't mess anything up
